/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'media',
  future: {
    hoverOnlyWhenSupported: true,
  },
  content: ['./index.html', './src/**/*.{vue,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['HarmonyOS Sans TC', 'HarmonyOS Sans SC', 'PingFang TC', 'Microsoft JhengHei', 'system-ui', 'sans-serif'],
        display: ['HarmonyOS Sans TC', 'HarmonyOS Sans SC', 'PingFang TC', 'Microsoft JhengHei', 'system-ui', 'sans-serif'],
        body: ['HarmonyOS Sans TC', 'HarmonyOS Sans SC', 'PingFang TC', 'Microsoft JhengHei', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        ink: {
          50: '#faf7f1',
          100: '#f0eae1',
          200: '#e1d9ce',
          300: '#c8beb2',
          400: '#a39a90',
          500: '#79726b',
          600: '#625c56',
          700: '#4b4742',
          800: '#3a3733',
          900: '#302d2a',
          950: '#211f1d',
        },
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        outline: 'rgb(var(--color-outline) / <alpha-value>)',
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
        secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--color-on-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        info: 'rgb(var(--color-info) / <alpha-value>)',
        'info-container': 'rgb(var(--color-info-container) / <alpha-value>)',
        'on-info-container': 'rgb(var(--color-on-info-container) / <alpha-value>)',
        success: 'rgb(var(--color-success) / <alpha-value>)',
        'success-container': 'rgb(var(--color-success-container) / <alpha-value>)',
        'on-success-container': 'rgb(var(--color-on-success-container) / <alpha-value>)',
        review: 'rgb(var(--color-review) / <alpha-value>)',
        'review-container': 'rgb(var(--color-review-container) / <alpha-value>)',
        'on-review-container': 'rgb(var(--color-on-review-container) / <alpha-value>)',
        pending: 'rgb(var(--color-pending) / <alpha-value>)',
        'pending-container': 'rgb(var(--color-pending-container) / <alpha-value>)',
        'on-pending-container': 'rgb(var(--color-on-pending-container) / <alpha-value>)',
        processing: 'rgb(var(--color-processing) / <alpha-value>)',
        'processing-container': 'rgb(var(--color-processing-container) / <alpha-value>)',
        'on-processing-container': 'rgb(var(--color-on-processing-container) / <alpha-value>)',
        infeasible: 'rgb(var(--color-infeasible) / <alpha-value>)',
        'infeasible-container': 'rgb(var(--color-infeasible-container) / <alpha-value>)',
        'on-infeasible-container': 'rgb(var(--color-on-infeasible-container) / <alpha-value>)',
        error: 'rgb(var(--color-error) / <alpha-value>)',
        'on-error': 'rgb(var(--color-on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        'warning-container': 'rgb(var(--color-warning-container) / <alpha-value>)',
        'on-warning-container': 'rgb(var(--color-on-warning-container) / <alpha-value>)',
      },
      boxShadow: {
        note: 'var(--shadow-control)',
        elevated: 'var(--shadow-card)',
        floating: 'var(--shadow-floating)',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
