// Generated by scripts/generate-backend-actions.mjs. Do not edit.
export const BACKEND_ACTION_POLICIES = {
  "cacheUserAvatar": {
    "group": "sensitive-write"
  },
  "completeInitialSetup": {
    "group": "admin-write"
  },
  "createAnnouncement": {
    "group": "admin-write"
  },
  "createAnnouncementComment": {
    "group": "sensitive-write"
  },
  "createComment": {
    "group": "sensitive-write"
  },
  "createFacility": {
    "group": "sensitive-write"
  },
  "createImageUploadSessions": {
    "group": "upload-write"
  },
  "createIssue": {
    "group": "sensitive-write"
  },
  "deleteAnnouncement": {
    "group": "admin-write"
  },
  "deleteAnnouncementComment": {
    "group": "sensitive-write"
  },
  "deleteComment": {
    "group": "sensitive-write"
  },
  "deleteFacility": {
    "group": "admin-write"
  },
  "deleteIssue": {
    "group": "admin-write"
  },
  "deleteUploadedImages": {
    "group": "upload-write"
  },
  "finalizeImageUploads": {
    "group": "upload-write"
  },
  "getAnnouncement": {
    "group": "read"
  },
  "getCategoryCatalog": {
    "group": "read"
  },
  "getCategoryManagement": {
    "group": "read"
  },
  "getContentVersions": {
    "group": "read"
  },
  "getAdminOverview": {
    "group": "read"
  },
  "getCurrentUserRole": {
    "group": "read"
  },
  "getSessionBootstrap": {
    "group": "read"
  },
  "getFacility": {
    "group": "read"
  },
  "getIssue": {
    "group": "read"
  },
  "getNotificationReadState": {
    "group": "read"
  },
  "getNotificationSnapshot": {
    "group": "read"
  },
  "getNotificationUnreadHint": {
    "group": "read"
  },
  "getPlatformDashboard": {
    "group": "read"
  },
  "getPushNotificationPreference": {
    "group": "read"
  },
  "getUserPublicProfiles": {
    "group": "read"
  },
  "listAnnouncementComments": {
    "group": "read"
  },
  "listAnnouncements": {
    "group": "read"
  },
  "listComments": {
    "group": "read"
  },
  "listFacilities": {
    "group": "read"
  },
  "listIssues": {
    "group": "read"
  },
  "listAdminAudit": {
    "group": "read"
  },
  "listAdminUsers": {
    "group": "read"
  },
  "listNotificationPages": {
    "group": "read"
  },
  "listRoleAssignments": {
    "group": "read"
  },
  "listUserIssues": {
    "group": "read"
  },
  "markNotificationsOpened": {
    "group": "general-write"
  },
  "moderateIssueStatus": {
    "group": "admin-write"
  },
  "registerPushToken": {
    "group": "sensitive-write"
  },
  "removeSupport": {
    "group": "sensitive-write"
  },
  "resolveUploadImageUrls": {
    "group": "upload-resolve"
  },
  "searchIssues": {
    "group": "read"
  },
  "saveCategoryManagement": {
    "group": "admin-write"
  },
  "savePlatformSettings": {
    "group": "admin-write"
  },
  "savePlatformFeatures": {
    "group": "admin-write"
  },
  "setAnnouncementLike": {
    "group": "sensitive-write"
  },
  "setUserAccessScope": {
    "group": "admin-write"
  },
  "setUserRestriction": {
    "group": "admin-write"
  },
  "toggleFacilityAffected": {
    "group": "sensitive-write"
  },
  "toggleSupport": {
    "group": "sensitive-write"
  },
  "unregisterPushToken": {
    "group": "sensitive-write"
  },
  "updateFacilityStatus": {
    "group": "admin-write"
  },
  "updateIssueResult": {
    "group": "admin-write"
  },
  "updatePushNotificationPreferences": {
    "group": "general-write"
  }
} as const;

export const BACKEND_ACTION_NAMES = [
  'cacheUserAvatar',
  'completeInitialSetup',
  'createAnnouncement',
  'createAnnouncementComment',
  'createComment',
  'createFacility',
  'createImageUploadSessions',
  'createIssue',
  'deleteAnnouncement',
  'deleteAnnouncementComment',
  'deleteComment',
  'deleteFacility',
  'deleteIssue',
  'deleteUploadedImages',
  'finalizeImageUploads',
  'getAnnouncement',
  'getCategoryCatalog',
  'getCategoryManagement',
  'getContentVersions',
  'getAdminOverview',
  'getCurrentUserRole',
  'getSessionBootstrap',
  'getFacility',
  'getIssue',
  'getNotificationReadState',
  'getNotificationSnapshot',
  'getNotificationUnreadHint',
  'getPlatformDashboard',
  'getPushNotificationPreference',
  'getUserPublicProfiles',
  'listAnnouncementComments',
  'listAnnouncements',
  'listComments',
  'listFacilities',
  'listIssues',
  'listAdminAudit',
  'listAdminUsers',
  'listNotificationPages',
  'listRoleAssignments',
  'listUserIssues',
  'markNotificationsOpened',
  'moderateIssueStatus',
  'registerPushToken',
  'removeSupport',
  'resolveUploadImageUrls',
  'searchIssues',
  'saveCategoryManagement',
  'savePlatformSettings',
  'savePlatformFeatures',
  'setAnnouncementLike',
  'setUserAccessScope',
  'setUserRestriction',
  'toggleFacilityAffected',
  'toggleSupport',
  'unregisterPushToken',
  'updateFacilityStatus',
  'updateIssueResult',
  'updatePushNotificationPreferences',
] as const;

export type BackendActionName = typeof BACKEND_ACTION_NAMES[number];
