// This file is generated automatically by scripts/generate-data-retention.mjs.
// Do not edit this file manually.

export const DATA_RETENTION = {
  "closedIssuesDays": 180,
  "closedFacilitiesDays": 180,
  "notificationsDays": 7,
  "realtimeEventsHours": 3,
  "outboxCompletedDays": 1,
  "outboxFailedDays": 3,
  "pushDeliverySentDays": 1,
  "pushDeliveryFailedDays": 3,
  "idempotencyHours": 24,
  "inactivePushTokensDays": 60,
  "deletionJobCompletedDays": 1,
  "deletionJobFailedDays": 3,
  "maintenanceRunsDays": 7,
  "roleAssignmentAuditDays": 365,
  "pendingUploadHours": 24,
  "unattachedUploadHours": 48,
  "failedUploadHours": 24
} as const;
