// This file is generated automatically by scripts/generate-data-retention.mjs.
// Do not edit this file manually.

export const DATA_RETENTION = {
  "closedIssuesEnabled": true,
  "closedIssuesDays": 365,
  "closedFacilitiesEnabled": true,
  "closedFacilitiesDays": 365,
  "announcementsDays": 730,
  "notificationsDays": 30,
  "realtimeEventsHours": 3,
  "outboxCompletedDays": 3,
  "outboxFailedDays": 14,
  "pushDeliverySentDays": 1,
  "pushDeliveryFailedDays": 7,
  "idempotencyHours": 24,
  "inactivePushTokensDays": 60,
  "pushTokenConfirmationDays": 7,
  "inactiveAvatarsDays": 180,
  "inactiveProfilePiiDays": 365,
  "expiredRestrictionsDays": 30,
  "deletionJobCompletedDays": 3,
  "deletionJobFailedDays": 30,
  "maintenanceRunsDays": 30,
  "roleAssignmentAuditDays": 365,
  "categoryConfigurationAuditDays": 365,
  "accessAssignmentAuditDays": 365,
  "pendingUploadHours": 24,
  "unattachedUploadHours": 48,
  "failedUploadHours": 24
} as const;
