// 每個 action 都要具體描述責任、資料操作與畫面結果；新增操作不得套空泛標題。
// [入口畫面, handler 的工作, 資料操作, 回應接收者的工作]
export const actionCopy = {
  getSessionBootstrap:['登入流程','彙整權限、分類與未讀快照','讀啟動資料並按需記錄造訪','Session store：建立登入後狀態'],
  getCurrentUserRole:['權限重新整理','重新解析角色與分類範圍','查角色、權限與分類指派','SessionAccess：更新可用操作'],
  listRoleAssignments:['負責成員編輯器','查完整成員或精確搜尋帳號','讀成員名單與名單版本','成員編輯器：建立名單草稿'],
  setUserAccessScope:['單筆授權 API','驗目標帳號並調整單一範圍','增刪分類指派並記錄稽核','呼叫端：採用正式授權結果'],
  saveScopeMembers:['負責成員編輯器','核對名單版本與整批變更','一次提交成員指派與稽核','成員編輯器：採用正式名單'],
  getUserPublicProfiles:['作者資訊元件','批次解析名稱與頭像網址','查公開資料與頭像版本','作者元件：顯示名稱與頭像'],
  cacheUserAvatar:['登入後頭像檢查','必要時抓 Google 頭像並上傳','更新頭像版本並排舊圖清理','頭像快取：採用正式頭像'],
  listAdminUsers:['使用者管理頁','搜尋帳號、角色與有效限制','分頁查使用者管理資料','使用者管理頁：顯示搜尋結果'],
  listAdminAudit:['管理紀錄頁','搜尋四類管理稽核','分頁查管理與指派稽核','管理紀錄頁：顯示操作紀錄'],
  listAdminActivity:['管理活動頁','依時間窗與游標查活動','查活動事件與稽核紀錄','活動列表：顯示明細與下一頁'],
  getAdminOverview:['管理總覽','彙整時間窗統計與健康狀態','查計數、活動與運行資料','管理總覽：更新統計與圖表'],
  listAccountAccessRules:['帳號限制列表','解析規則期限、命中數與版本','查 UID 與 Email 字首規則','限制列表：顯示正式規則'],
  previewAccountAccessRule:['限制規則編輯器','估算字首規則會限制幾人','只讀比對字首與正式管理員','確認視窗：顯示預估命中數'],
  saveAccountAccessRule:['限制規則編輯器','核對版本並計算正式期限','新增或更新精確限制規則','限制編輯器：採用正式期限'],
  deleteAccountAccessRule:['限制移除確認','核對版本並解析剩餘限制','刪指定 UID 或字首規則','使用者詳情：更新有效限制'],
  listIssues:['提案列表','依條件與可見性查提案','讀提案、附議與內容版本','提案列表：套用分頁與件數'],
  searchIssues:['提案搜尋欄','驗搜尋長度與資料可見性','搜尋可見標題、內容與作者','提案列表：顯示搜尋結果'],
  listUserIssues:['我的提案頁','只查目前帳號的提案','按作者 UID 查提案與游標','我的提案頁：套用查詢結果'],
  getIssue:['提案詳情入口','驗詳情存取與提案規則','讀提案、附議狀態與快照','提案詳情：採用正式內容'],
  listIssueSupporters:['附議者名單','先驗提案可見性再查附議者','讀支持者與公開個人資料','附議名單：顯示支持者'],
  createIssue:['提案編輯器','驗分類、字數與圖片所有權','建提案、保存規則並附著圖片','提案編輯器：清草稿並開詳情'],
  toggleSupport:['附議按鈕','驗狀態、作者與附議截止','新增支持者並重算附議人數','附議按鈕：採正式人數或復原'],
  removeSupport:['取消附議按鈕','驗期限並只移除本人支持','刪支持紀錄並重算附議人數','附議按鈕：採正式人數或復原'],
  listComments:['提案討論區','驗提案可見性與留言讀取規則','分頁讀提案留言與回覆','討論區：合併留言分頁'],
  createComment:['提案留言編輯器','驗留言開關、回覆層級與圖片','建留言、附著圖片並更新計數','留言編輯器：清本次草稿'],
  deleteComment:['提案留言選單','驗留言作者或分類管理範圍','刪留言、回覆並排圖片清理','提案討論區：移除留言與回覆'],
  moderateIssueStatus:['提案管理表單','驗管理範圍、狀態與結案結果','一起更新狀態、結果與期限','提案詳情：顯示正式處理狀態'],
  updateIssueResult:['提案結果編輯器','驗管理範圍與結案結果不可空','更新處理結果並保留原狀態','提案詳情：更新處理結果'],
  deleteIssue:['提案刪除確認','驗分類管理權或作者刪除開關','刪提案及關聯並排外部清理','提案頁：離開已刪內容'],
  listFacilities:['設施回報列表','套分類、搜尋、狀態與排序','讀設施回報、反應與版本','設施列表：套用分頁與件數'],
  getFacility:['設施詳情入口','解析管理權與作者刪除權','讀設施回報與個人反應','設施詳情：顯示位置與結果'],
  createFacility:['設施回報編輯器','驗位置、分類與圖片所有權','建待處理回報並附著圖片','回報編輯器：清草稿並開詳情'],
  toggleFacilityAffected:['我也遇到按鈕','增刪本人的受影響紀錄','更新受影響者與正式人數','我也遇到：採正式人數或復原'],
  updateFacilityStatus:['設施管理表單','驗分類管理範圍與處理結果','更新處理狀態及開始結案時間','設施詳情：顯示正式處理結果'],
  deleteFacility:['設施刪除確認','驗管理範圍或作者刪除開關','刪回報與反應並排圖片清理','設施頁：離開已刪回報'],
  listAnnouncements:['公告列表','依發布時間與游標查公告','讀公告、本人按讚與版本','公告列表：套用下一頁內容'],
  getAnnouncement:['公告詳情入口','讀公告與本人的按讚狀態','查公告內容與當前留言開關','公告詳情：呈現內容與討論'],
  getAnnouncementUnreadHint:['導覽新公告提示','比較發布時間與已看水位','查公告與公告已讀時間','導覽列：更新新公告提示'],
  markAnnouncementsOpened:['公告列表開啟事件','只向前推進公告已讀水位','更新公告 opened_at','導覽列：清除已看公告提示'],
  createAnnouncement:['公告編輯器','驗公告管理權、文字與圖片','發布公告並附著圖片','公告編輯器：清草稿並開詳情'],
  deleteAnnouncement:['公告刪除確認','驗公告管理權並保留清理責任','刪公告、讚、留言並排清理','公告頁：離開已刪公告'],
  setAnnouncementLike:['公告按讚按鈕','依期望 liked 狀態增刪本人讚','增刪按讚紀錄並重算人數','按讚按鈕：採正式狀態或復原'],
  listAnnouncementComments:['公告討論區','驗公告存在並解析分頁條件','分頁讀公告留言與回覆','公告討論區：合併留言分頁'],
  createAnnouncementComment:['公告留言編輯器','驗平台開關、回覆與圖片規則','建公告留言並更新計數','公告留言編輯器：清本次草稿'],
  deleteAnnouncementComment:['公告留言選單','驗作者身分或公告管理權','刪留言、回覆並排圖片清理','公告討論區：移除留言與回覆'],
  getNotificationSnapshot:['通知頁開啟事件','合併三來源首頁與已讀水位','讀可見且未到期的通知','通知頁：呈現初始通知快照'],
  listNotificationPages:['通知載入更多','分別處理三來源的微秒游標','分頁讀可見且未到期通知','通知列表：合併排序並去重'],
  getNotificationReadState:['通知紅點元件','取得四種已讀水位','讀本人的 notification_states','通知元件：更新已讀判斷'],
  getNotificationUnreadHint:['通知紅點檢查','驗來源權限、期限與水位','查是否存在可見未讀通知','導覽列：更新未讀紅點'],
  markNotificationsOpened:['通知頁已讀事件','以後端時間向前推進水位','更新本人各來源 opened_at','通知頁：更新已讀樣式'],
  getPushNotificationPreference:['裝置通知設定','查此裝置的正式註冊狀態','讀本人裝置的 Push token','通知設定：合併權限與註冊狀態'],
  getPlatformAdminNotificationPreferences:['管理員通知設定','確認管理員並讀個人偏好','讀本人三類通知偏好','通知設定：顯示本人三個開關'],
  updatePlatformAdminNotificationPreferences:['管理員通知開關','驗管理員並更新本人偏好','保存本人的三個通知布林值','通知設定：採用正式個人偏好'],
  registerPushToken:['Push 註冊與確認','驗裝置、token 與帳號歸屬','登記 token 並更新確認時間','Push 狀態：確認裝置已登記'],
  unregisterPushToken:['裝置註冊移除事件','只移除本人這臺裝置的註冊','刪本人 deviceId 的 token','裝置狀態：移除 Push 登記'],
  createImageUploadSessions:['附件上傳流程','驗實際分類上限並簽上傳參數','建 pending upload 與所有權','附件流程：拿簽名直傳圖片'],
  finalizeImageUploads:['Cloudinary 上傳完成事件','驗供應商簽名、尺寸與大小','將已驗證 upload 改成 ready','附件流程：取得可附著圖片 ID'],
  deleteUploadedImages:['未送出附件清理','驗圖片屬本人且尚未附著','刪 upload 並建圖片刪除工作','附件流程：移除待清理附件'],
  resolveUploadImageUrls:['Markdown 圖片元件','驗內容可見性並簽媒體網址','查 upload 與附著內容存取資料','Markdown：顯示可存取的圖片'],
  getCategoryCatalog:['分類與功能載入','組分類、功能與圖片契約','讀分類、setup 與 runtime 設定','Catalog store：供導覽與表單使用'],
  getCategoryManagement:['分類設定編輯器','驗管理權並算兩組設定版本','讀分類、平台設定與版本','設定編輯器：建立正式草稿基準'],
  estimateCategoryPolicyChanges:['分類設定確認','核對版本並估留言批次範圍','只讀估算既有內容的影響筆數','確認視窗：顯示留言套用範圍'],
  saveCategoryManagement:['分類設定儲存','核對版本並驗分類完整草稿','保存分類、開關、稽核與工作','分類編輯器：採正式分類與版本'],
  savePlatformFeatures:['功能開關儲存','驗管理權並更新平台功能','保存功能開關並排留言工作','Catalog store：更新功能與守門規則'],
  savePlatformSettings:['平台設定儲存','核對版本並選本次保留範圍','保存圖片與保留設定及工作','平台編輯器：採正式設定與進度'],
  estimateRetentionCleanup:['保留設定確認','核對版本並分開刪除與更新','只讀估算本次清理與期限修復','確認視窗：顯示刪除及更新筆數'],
  listPlatformJobs:['設定套用進度','查待處理、失敗與近期工作','讀工作狀態、估算與處理筆數','進度面板：顯示完成或失敗'],
  completeInitialSetup:['首次設定表單','驗管理員與必需分類並防重複','完成 singleton 並建立初始分類','登入流程：重新載入後進入首頁'],
  getRuntimePolicies:['政策版本重新整理','讀正式政策與最新版本','查 operations_settings','政策 store：替換正式營運政策'],
  getProviderDiagnostics:['供應商診斷頁','驗管理員並選診斷供應商','查 Cloudinary、Cloudflare 或 logs API','診斷頁：顯示當次供應商回應'],
  getOperationsConsole:['系統運行頁','依查詢模式拆讀容量與工作','分段讀工作、錯誤與政策歷史','系統面板：分段顯示正式快照'],
  saveOperationPolicies:['營運政策編輯器','核對版本、原因與契約範圍','保存政策、新版本與前後歷史','政策 store：立即採正式儲存值'],
  retryOperationalWork:['失敗工作重試按鈕','重設選定工作並還原清理責任','將工作改 pending 並重設重試','系統面板：刷新待重試工作'],
  clearOperationalErrors:['清除錯誤紀錄確認','只清每日應用錯誤聚合','刪 operational_errors 聚合列','錯誤面板：刷新聚合紀錄'],
  clearScheduledWork:['清除排程工作確認','取消待辦並放棄清理 backlog','取代未完工作並刪清理 backlog','工作面板：顯示取消後狀態'],
  rebuildNotionArchive:['重建 Notion 按鈕','驗啟用並建立唯一重建工作','重設對映與舊工作並排重建','系統面板：追蹤 Notion 重建'],
  getPlatformDashboard:['系統健康面板','彙整分類統計與待辦健康快照','查計數、工作、投遞與圖片','健康面板：顯示積壓與失敗'],
  getContentVersions:['前景與即時重連事件','讀三類內容的正式版本','查 content_versions','內容快取：清失效資料並重讀'],
};

export function describeAction(id, action) {
  const copy = actionCopy[id];
  if (!copy) throw new Error('缺具體 action 卡片標題：'+id);
  const module = action.refs[0].split('/').at(-1).replace('.ts','');
  return {input:copy[0]+'：'+action.title,request:'backend-action：送出'+action.title,business:module+'：'+copy[1],storage:(id==='getProviderDiagnostics'?'供應商 API':'PostgreSQL')+'：'+copy[2],response:copy[3]};
}
